In [1]:
#given code
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables

#Here array_list is numpy array and variable list is just a list as we know in earlier.
#the data type of array list is u1,means unsigned integer with 1 byte of memory 
#knowing the data type of array list using inbuilt function datatype
array_list.dtype

dtype('<U1')

In [7]:
#using type function to know the variable list type.
type(list_)

list

In [8]:
type(array_list)

numpy.ndarray

In [9]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and
#arra_list.
#taking variable list
list_ = [ '1' , '2' , '3' , '4' , '5' ]
#iterating through each element in list
for element in list_:
    #printing the type
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
#taking rray list which is already given at first
array_list
print(array_list)
#iteratin through entire array_list
for element in array_list:
    print(element.dtype)

['1' '2' '3' '4' '5']
<U1
<U1
<U1
<U1
<U1


In [16]:
#given code
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)

In [17]:
'''Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.'''
array_list

array([1, 2, 3, 4, 5])

In [18]:
#knowing the data types of both variable list array list after slight change in array list
type(list_)

list

In [19]:
array_list.dtype

dtype('int64')

In [21]:
#taking variable list
list_ = [ '1' , '2' , '3' , '4' , '5' ]
print("variable list is: ",list_)
print("Datatype of each elemnt in variable list is ...")
#iterating through each element in list
for element in list_:
    #printing the type
    print(type(element))
    
#taking array list which is already given at first
array_list
print("Array-list is: ",array_list)
print("Data type each element in array_list is...")
#iteratin through entire array_list
for element in array_list:
    print(element.dtype)

variable list is:  ['1', '2', '3', '4', '5']
Datatype of each elemnt in variable list is ...
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Array-list is:  [1 2 3 4 5]
Data type each element in array_list is...
int64
int64
int64
int64
int64


In [22]:
#given code
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [23]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size
#findind the shape and size of given num_array using inbuilt functions
#shape which gives the order of matrix that is no.of rows , no.of columns 
np.shape(num_array)

(2, 3)

In [26]:
#size gives the dimension of given num_array
np.size(num_array)

6

In [27]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#importing numpy module
import numpy as np
#creating zeros of 3*3 using numpy creation function ,which is np.zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

#numpy is already in our lab
#creating identity matrix with shape(5,5) using inbuilt function identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])